/* tslint:disable */
/* eslint-disable */
/**
 * Usr API
 * CRUD műveletek a Usr erőforráson.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidationErrorAllOfDetails
 */
export interface ValidationErrorAllOfDetails {
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorAllOfDetails
     */
    field?: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorAllOfDetails
     */
    issue?: string;
}

/**
 * Check if a given object implements the ValidationErrorAllOfDetails interface.
 */
export function instanceOfValidationErrorAllOfDetails(value: object): value is ValidationErrorAllOfDetails {
    return true;
}

export function ValidationErrorAllOfDetailsFromJSON(json: any): ValidationErrorAllOfDetails {
    return ValidationErrorAllOfDetailsFromJSONTyped(json, false);
}

export function ValidationErrorAllOfDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorAllOfDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'] == null ? undefined : json['field'],
        'issue': json['issue'] == null ? undefined : json['issue'],
    };
}

export function ValidationErrorAllOfDetailsToJSON(json: any): ValidationErrorAllOfDetails {
    return ValidationErrorAllOfDetailsToJSONTyped(json, false);
}

export function ValidationErrorAllOfDetailsToJSONTyped(value?: ValidationErrorAllOfDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'issue': value['issue'],
    };
}

