name: Local Docker build (UI)

on:
  push:
    branches: [ main, master ]
    paths:
      - "Dockerfile"
      - "scripts/**"
      - "szamlazzponthu-test-ui-app/**"
      - ".github/workflows/ui-docker.yml"

permissions:
  contents: read

jobs:
  build-local-image:
    runs-on: [ self-hosted, linux, docker ]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build local image (no push)
        run: |
          APP=szamlazz-ui
          TAG=latest
          docker build \
            -f Dockerfile \
            -t "${APP}:${TAG}" \
            --build-arg APP_DIR=szamlazzponthu-test-ui-app \
            .
